Ama romach
DanielDavidyan/Angular pull request #1
Opened 2020-09-23 13:54 UTC by DanielDavidyan

2020-09-24 07:11 UTC, 1Like1Prayer requested changes

2020-09-24 08:12 UTC, DanielDavidyan commented on src/app/cart-product/cart-product.component.ts
> +    this.productsService.getProduct(this.cartProduct).subscribe(val => this.product = val);
this.product is Product type not Observable

2020-09-29 09:19 UTC, DanielDavidyan commented on src/app/product/product.component.html
> +      <button *ngIf="isExistInCart(product)" (click)="removeProduct(product)" class="ui primary button"
*ngIf is better here

2020-10-11 01:09 UTC, 1Like1Prayer requested changes

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-list/cart-list.component.ts
> +    productsInCart.map(cartProducts => {
cartProducts --> cartProduct

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-list/cart-list.component.html
> +      <h3> Total Price: <i class="shekel sign icon shekel-sign-icon"></i> {{totalPrice | async}} </h3>
don't use style attributes in html!

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-product/cart-product.component.ts
> +  createArray(size: number): number[] {
make it a private function

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-product/cart-product.component.ts
> +  updateProductAmount(amount: any): void {
type

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-product/cart-product.component.ts
> +  updateInput(event: any): void {
type

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-product/cart-product.component.ts
> +  updateInput(event: any): void {
give proper name

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-product/cart-product.component.ts
> +    this.cartProductService.updateProductAmount(this.cartProductName, event.target.value);
try to send the event.taget.value from the html and not here

2020-10-11 01:09 UTC, 1Like1Prayer commented on src/app/cart-module/cart-product/cart-product.component.ts
> +  createArray(size: number): number[] {
too long and sloppy, use es6 shortcuts to make it a one liner

2020-10-15 08:52 UTC, DanielDavidyan commented on src/app/nav-bar/nav-bar.component.ts
> +    this.howManyProducts(this.cartProductsService.getCartProducts());
I cant because this.numberOfProducts is Observable<number>

2020-10-20 08:28 UTC, DanielDavidyan commented on src/app/app-routing.module.ts
> +  {path: '', component: IndexComponent},
we will talk about it

2020-10-20 08:31 UTC, DanielDavidyan commented on src/app/products-module/product/product.component.html
> +        *ngIf="!isExistInCart(cartProductName) &&
I think it's better that way, ng-template complicates it.
we will talk about it.

2020-10-28 09:06 UTC, 1Like1Prayer requested changes

2020-10-28 12:53 UTC, closed without merging