Angular testing
DanielDavidyan/Angular pull request #2
Opened 2020-11-29 08:02 UTC by DanielDavidyan

2020-11-29 08:19 UTC, 1Like1Prayer requested changes

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/app-routing.module.ts
> +// const routes: Routes = [
remove

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  // when(service.getProduct(productName)).thenReturn(of(product));
remove

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  // when(service.getProduct(productName)).thenReturn(of(product));
remove

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  test('should be created', () => {
test --> it

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  it('getProducts', () => {
all tests should be in the format of 'should ....'

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  it('getProduct', () => {
check what happens if you try to get a product that doesn't exist

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  it('updateLimit', () => {
check what happens when you try to update a product that doesn't exist
check what happens when you try to update with a number that exceeds the product limit

2020-11-29 08:19 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +    expect(service.getProduct(productName)['destination']['_value'][0]).toEqual((product));
try to remove the `['destination']['_value']`

2020-11-29 13:19 UTC, DanielDavidyan commented on src/app/products/product-service/product.service.spec.ts
> +  it('getProduct', () => {
I added a test

2020-11-30 13:31 UTC, 1Like1Prayer requested changes

2020-11-30 13:31 UTC, 1Like1Prayer commented on src/app/products/product-details/product-details.component.spec.ts
> +  const router: any = mock(ActivatedRoute);
check if there is a type available.

2020-11-30 13:31 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +      console.log('exist');
remove console

2020-11-30 13:31 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +      console.log('doesnt exist');
remove console

2020-11-30 13:31 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  it('should get an non-existent product', () => {
`should return undefined when trying to get a non existent product`

2020-11-30 13:31 UTC, 1Like1Prayer commented on src/app/products/product-service/product.service.spec.ts
> +  it('should be updateLimit', () => {
`should product update limit when called`

2020-11-30 13:31 UTC, 1Like1Prayer commented on src/app/cart/cart-list/cart-list.component.spec.ts
> +  it('checkout', () => {
`should checkout from cart when called`

2020-11-30 14:04 UTC, merged